// Code generated by goa v2.0.0-wip, DO NOT EDIT.
//
// servicea authentication logic.
//
// Command:
// $ goa example github.com/shihanng/gaegoasample/svc/servicea/design -o
// /home/shihanng/go/src/github.com/shihanng/gaegoasample/svc/servicea

package servicea
