swagger: "2.0"
info:
  title: The service a
  version: ""
host: localhost:8080
paths:
  /api/info:
    get:
      tags:
      - api
      summary: info api
      description: Show info of the service
      operationId: api#info
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/InfoResponseBody'
      schemes:
      - http
definitions:
  InfoResponseBody:
    title: 'Mediatype identifier: application/gaegoasample.info; view=default'
    type: object
    properties:
      id:
        type: string
        description: ID of the service
        example: Est qui.
      service_name:
        type: string
        description: Service's name
        example: Sit libero qui aperiam distinctio et.
      version:
        type: string
        description: Service's version
        example: Numquam ullam alias repudiandae ipsam quo.
    example:
      id: Reiciendis et ipsam.
      service_name: Dicta est consequatur totam omnis dolores nemo.
      version: Dicta ratione dignissimos itaque facilis voluptas.
